Add chaincode packaging scripts
Signed-off-by: James Taylor <jamest@uk.ibm.com>

diff --git a/devenv-cloud-config.yaml b/devenv-cloud-config.yaml
--- a/devenv-cloud-config.yaml
+++ b/devenv-cloud-config.yaml
@@ -76,6 +76,97 @@ write_files:
 - path: /etc/nsswitch.conf
   content: |
     hosts: files dns
+- path: /usr/local/bin/pkgccaas
+  permissions: '0755'
+  content: |
+    #!/usr/bin/env sh
+
+    # TODO:
+    # - download pkgccaas script from git instead of embedding it in yaml?
+    # - same for pkgk8s, or combine the two?
+
+    usage() {
+        echo "Usage: pkgccaas -l <label> -a <address> [-m <META-INF directory>]"
+    }
+
+    error_exit() {
+        echo "${1:-"Unknown Error"}" 1>&2
+        exit 1
+    }
+
+    while getopts "hl:a:m:" opt; do
+        case "$opt" in
+            h)
+                usage
+                exit 0
+                ;;
+            l)
+                label=${OPTARG}
+                ;;
+            m)
+                metainf=${OPTARG}
+                ;;
+            a)
+                address=${OPTARG}
+                ;;
+            *)
+                usage
+                exit 1
+                ;;
+        esac
+    done
+    shift $((OPTIND-1))
+
+    if [ -z "$label" ] || [ -z "$address" ]; then
+        usage
+        exit 1
+    fi
+
+    metadir=$(basename "$metainf")
+    if [ -n "$metainf" ]; then
+        if [ "META-INF" != "$metadir" ]; then
+            error_exit "Invalid chaincode META-INF directory $metadir: directory name must be 'META-INF'"
+        elif [ ! -d "$metainf" ]; then
+            error_exit "Cannot find directory $metadir"
+        fi
+    fi
+
+    prefix=$(basename "$0")
+    tempdir=$(mktemp -d -t "$prefix.XXXXXXXX") || error_exit "Error creating temporary directory"
+
+    if [ -n "$DEBUG" ]; then
+        echo "label = $label"
+        echo "address = $address"
+        echo "tempdir = $tempdir"
+        echo "metainf = $metainf"
+    fi
+
+    mkdir -p "$tempdir/src"
+    cat > "$tempdir/src/connection.json" << CONNECTION-EOF
+    {
+      "address": "${address}",
+      "dial_timeout": "10s",
+      "tls_required": false
+    }
+    CONNECTION-EOF
+
+    if [ -n "$metainf" ]; then
+        cp -a "$metainf" "$tempdir/src/"
+    fi
+
+    mkdir -p "$tempdir/pkg"
+    cat << METADATA-EOF > "$tempdir/pkg/metadata.json"
+    {
+        "type": "ccaas",
+        "label": "$label"
+    }
+    METADATA-EOF
+
+    tar -C "$tempdir/src" -czf "$tempdir/pkg/code.tar.gz" .
+
+    tar -C "$tempdir/pkg" -czf "$label.tgz" metadata.json code.tar.gz
+
+    rm -Rf "$tempdir"
 - path: /usr/local/bin/setup-fabric
   permissions: '0755'
   content: |
@@ -113,6 +204,8 @@ write_files:
 
     # TODO: just replace the external builders completely?
     yq e 'del(.vm.endpoint) | (.chaincode.externalBuilders[] | select(.name == "ccaas_builder") | .path) = ("${HOME}/fabric-builders/ccaas" | envsubst(ne)) | .chaincode.externalBuilders += { "name": "k8s_builder", "path": "${HOME}/fabric-builders/k8s" | envsubst(ne), "propagateEnvironment": [ "CORE_PEER_ID", "KUBECONFIG_PATH" ] }' -i "$HOME/fabric-samples/config/core.yaml"
+
+    wget -qO- https://raw.githubusercontent.com/hyperledgendary/package-k8s-chaincode-action/main/pkgk8scc.sh > /usr/local/bin/pkgk8scc && chmod 0755 /usr/local/bin/pkgk8scc
 
 runcmd:
   - wget -P /tmp/ https://go.dev/dl/go1.18.7.linux-arm64.tar.gz
